export const
  GET_WEEKLY_SLOTS = 'GET_WEEKLY_SLOTS',
  WEEKLY_SLOTS_RECEIVED = 'WEEKLY_SLOTS_RECEIVED',
  WEEKLY_SLOTS_ERROR = 'WEEKLY_SLOTS_ERROR',
  BOOK_SLOT = 'BOOK_SLOT',
  BOOK_SLOT_SUCCESSFUL = 'BOOK_SLOT_SUCCESSFUL',
  BOOK_SLOT_ERROR = 'BOOK_SLOT_ERROR'